import "server-only";
import { Resend } from "resend";
export function getResend() { const key = process.env.RESEND_API_KEY; if (!key) throw new Error("RESEND_API_KEY is not configured."); return new Resend(key); }

const escape = (value: string) => value.replace(/[&<>"']/g, (character) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[character]!);
export function pickReminderHtml(input: { name: string; week: number; count: number; matchups: string[]; kind: "thursday" | "sunday"; unsubscribeUrl: string }) {
  const title = input.kind === "thursday" ? "Thursday kickoff is coming" : "Sunday picks are still open";
  return `<!doctype html><html><body style="margin:0;background:#050505;color:#f9fafb;font-family:Arial,sans-serif"><div style="max-width:560px;margin:0 auto;padding:36px 20px"><div style="color:#f59e0b;font-weight:700">🥨 PRETZEL QUEST</div><h1 style="font-size:28px;margin:18px 0 10px">${title}</h1><p style="color:#d1d5db;line-height:1.6">Hi ${escape(input.name)}, you have ${input.count} unpicked ${input.count === 1 ? "game" : "games"} for Week ${input.week}.</p><div style="background:#0b1220;border:1px solid #273244;border-radius:12px;padding:16px;margin:20px 0">${input.matchups.map((matchup) => `<div style="padding:6px 0;color:#e5e7eb">${escape(matchup)}</div>`).join("")}</div><a href="https://pretzel.quest/week/${input.week}" style="display:inline-block;background:#2563eb;color:white;text-decoration:none;border-radius:10px;padding:12px 18px;font-weight:700">Finish my picks</a><p style="margin-top:28px;color:#6b7280;font-size:12px">You can change reminder settings anytime from your Pretzel Quest profile or <a href="${escape(input.unsubscribeUrl)}" style="color:#9ca3af">unsubscribe from all pick reminders</a>.</p></div></body></html>`;
}

export function operationalAlertHtml(input: { title: string; summary: string; details: string[]; adminUrl: string }) {
  return `<!doctype html><html><body style="margin:0;background:#050505;color:#f9fafb;font-family:Arial,sans-serif"><div style="max-width:560px;margin:0 auto;padding:36px 20px"><div style="color:#f59e0b;font-weight:700">🥨 PRETZEL QUEST</div><h1 style="font-size:28px;margin:18px 0 10px">${escape(input.title)}</h1><p style="color:#d1d5db;line-height:1.6">${escape(input.summary)}</p><div style="background:#0b1220;border:1px solid #273244;border-radius:12px;padding:16px;margin:20px 0">${input.details.map((detail) => `<div style="padding:6px 0;color:#e5e7eb">${escape(detail)}</div>`).join("")}</div><a href="${escape(input.adminUrl)}" style="display:inline-block;background:#dc2626;color:white;text-decoration:none;border-radius:10px;padding:12px 18px;font-weight:700">Open Admin dashboard</a><p style="margin-top:28px;color:#6b7280;font-size:12px">This operational alert was sent only to Pretzel Quest administrators.</p></div></body></html>`;
}
