"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { ShareImageButton } from "@/components/ShareImageButton";
import { getGamesBySeason, type GameRow } from "@/lib/gamesDb";
import { getUserPicks } from "@/lib/picksDb";
import { getMyPools, getPoolStandings, type Pool } from "@/lib/poolsDb";
import { supabase } from "@/lib/supabaseClient";
import { buildWeeklyRecap } from "@/lib/weeklyRecap";
import type { LeaderboardRow } from "@/lib/leaderboardDb";

type PoolContext = { rank: number | null; movement: number; winner: string | null; members: number };
function cumulativeRank(weeks: LeaderboardRow[][], userId: string) { const totals = new Map<string, { name: string; points: number }>(); for (const rows of weeks) for (const row of rows) { const current = totals.get(row.user_id) ?? { name: row.display_name, points: 0 }; current.points += row.points; totals.set(row.user_id, current); } const ranked = [...totals.entries()].sort((a, b) => b[1].points - a[1].points || a[1].name.localeCompare(b[1].name)); const index = ranked.findIndex(([id]) => id === userId); return index >= 0 ? index + 1 : null; }

export default function RecapPage() {
  const [games, setGames] = useState<GameRow[]>([]); const [picks, setPicks] = useState<Record<string, string>>({});
  const [pools, setPools] = useState<Pool[]>([]); const [poolId, setPoolId] = useState(""); const [week, setWeek] = useState(1);
  const [userId, setUserId] = useState<string | null>(null); const [displayName, setDisplayName] = useState("Pretzel Quest player");
  const [poolContext, setPoolContext] = useState<PoolContext | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  useEffect(() => { let cancelled = false; async function load() { try { const [{ data }, rows] = await Promise.all([supabase.auth.getUser(), getGamesBySeason(2026)]); if (!data.user) { if (!cancelled) { setGames(rows); setLoading(false); } return; } const [saved, userPools, profile] = await Promise.all([getUserPicks(data.user.id), getMyPools(), supabase.from("profiles").select("display_name").eq("user_id", data.user.id).maybeSingle()]); if (cancelled) return; setGames(rows); setPicks(saved); setPools(userPools); setUserId(data.user.id); setDisplayName(profile.data?.display_name || data.user.email?.split("@")[0] || "Pretzel Quest player"); const completed = rows.filter((game) => game.status === "final"); if (completed.length) setWeek(Math.max(...completed.map((game) => game.week))); } catch (loadError) { if (!cancelled) setError(loadError instanceof Error ? loadError.message : "Unable to build your recap."); } finally { if (!cancelled) setLoading(false); } } void load(); return () => { cancelled = true; }; }, []);
  useEffect(() => { if (!poolId || !userId) { setPoolContext(null); return; } let cancelled = false; async function loadPool() { try { const weeklyPromises = Array.from({ length: week }, (_, index) => getPoolStandings(poolId, index + 1)); const allWeeks = await Promise.all(weeklyPromises); if (cancelled) return; const currentRank = cumulativeRank(allWeeks, userId!); const previousRank = week > 1 ? cumulativeRank(allWeeks.slice(0, -1), userId!) : currentRank; const currentWeek = allWeeks.at(-1) ?? []; setPoolContext({ rank: currentRank, movement: currentRank && previousRank ? previousRank - currentRank : 0, winner: currentWeek[0]?.points > 0 ? currentWeek[0].display_name : null, members: currentWeek.length }); } catch (loadError) { if (!cancelled) setError(loadError instanceof Error ? loadError.message : "Unable to load pool recap."); } } void loadPool(); return () => { cancelled = true; }; }, [poolId, userId, week]);
  const recap = useMemo(() => buildWeeklyRecap(games, picks, week), [games, picks, week]);
  const selectedPool = pools.find((pool) => pool.pool_id === poolId);
  const imageUrl = `/api/share/recap?${new URLSearchParams({ name: displayName, week: String(week), correct: String(recap.correct), total: String(recap.finalPicks), points: String(recap.points), agreement: recap.agreement === null ? "—" : `${recap.agreement}%`, best: recap.bestUpset?.team ?? "No upset pick", pool: selectedPool?.name ?? "", rank: poolContext?.rank ? `#${poolContext.rank}` : "" }).toString()}`;
  return <main className="mx-auto max-w-5xl p-6"><div className="max-w-3xl"><p className="text-sm font-medium uppercase tracking-widest text-amber-400">🥨 Weekly rewind</p><h1 className="mt-1 text-3xl font-semibold">My Recap</h1><p className="mt-2 text-gray-400">Your weekly scorecard, model comparison, and pool results in one place.</p></div>
    {loading ? <div className="mt-8 rounded-xl border border-gray-800 p-6">Building your recap…</div> : null}{error ? <div className="mt-8 rounded-xl border border-red-900 bg-red-950/30 p-5 text-red-200">{error}</div> : null}
    {!loading && !userId ? <div className="mt-8 rounded-xl border border-blue-900 bg-blue-950/30 p-6"><h2 className="font-semibold">Log in to see your recap</h2><p className="mt-2 text-sm text-gray-300">Recaps use your saved picks and pool memberships.</p><Link href="/login?next=/recap" className="mt-4 inline-block text-blue-300 underline">Log in</Link></div> : null}
    {!loading && userId ? <><div className="mt-6 flex flex-wrap items-end gap-3"><label className="text-sm text-gray-300">Week<select value={week} onChange={(event) => setWeek(Number(event.target.value))} className="mt-1 block rounded-xl border border-gray-700 bg-gray-950 px-5 py-3 text-white">{Array.from({ length: 18 }, (_, index) => <option key={index + 1} value={index + 1}>Week {index + 1}</option>)}</select></label>{pools.length ? <label className="min-w-56 text-sm text-gray-300">Pool<select value={poolId} onChange={(event) => setPoolId(event.target.value)} className="mt-1 block w-full rounded-xl border border-gray-700 bg-gray-950 px-4 py-3 text-white"><option value="">No pool</option>{pools.map((pool) => <option key={pool.pool_id} value={pool.pool_id}>{pool.name}</option>)}</select></label> : null}{recap.finalPicks ? <ShareImageButton imageUrl={imageUrl} fileName={`pretzel-quest-week-${week}-recap.png`} label="Share recap" /> : null}</div>
      {!recap.finalPicks ? <div className="mt-8 rounded-2xl border border-gray-800 bg-gray-950 p-6"><h2 className="text-xl font-semibold">Week {week} recap isn’t ready yet</h2><p className="mt-2 text-sm text-gray-400">It will appear after at least one game is final and you have a pick for it. {recap.pending} game{recap.pending === 1 ? " is" : "s are"} still awaiting a result.</p></div> : <><section className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><div className="rounded-2xl border border-gray-800 bg-gray-950 p-5"><p className="text-xs uppercase tracking-wider text-gray-500">Record</p><p className="mt-2 text-3xl font-bold">{recap.correct}-{recap.finalPicks - recap.correct}</p><p className="mt-1 text-sm text-gray-400">{recap.accuracy}% correct</p></div><div className="rounded-2xl border border-gray-800 bg-gray-950 p-5"><p className="text-xs uppercase tracking-wider text-gray-500">Points</p><p className="mt-2 text-3xl font-bold text-blue-300">{recap.points}</p><p className="mt-1 text-sm text-gray-400">Pick + correct bonuses</p></div><div className="rounded-2xl border border-gray-800 bg-gray-950 p-5"><p className="text-xs uppercase tracking-wider text-gray-500">Model agreement</p><p className="mt-2 text-3xl font-bold">{recap.agreement}%</p><p className="mt-1 text-sm text-gray-400">Same side as the model</p></div><div className="rounded-2xl border border-gray-800 bg-gray-950 p-5"><p className="text-xs uppercase tracking-wider text-gray-500">Games remaining</p><p className="mt-2 text-3xl font-bold">{recap.pending}</p><p className="mt-1 text-sm text-gray-400">Recap updates as results arrive</p></div></section>
        <section className="mt-6 grid gap-4 md:grid-cols-2"><div className="rounded-2xl border border-emerald-900 bg-emerald-950/20 p-5"><p className="text-xs uppercase tracking-wider text-emerald-400">Best upset</p>{recap.bestUpset ? <><h2 className="mt-2 text-xl font-semibold">{recap.bestUpset.team}</h2><p className="mt-1 text-sm text-gray-300">Won as a {recap.bestUpset.probability}% model underdog over {recap.bestUpset.opponent}.</p></> : <p className="mt-2 text-sm text-gray-400">No correct underdog pick this week.</p>}</div><div className="rounded-2xl border border-rose-900 bg-rose-950/20 p-5"><p className="text-xs uppercase tracking-wider text-rose-400">Biggest miss</p>{recap.biggestMiss ? <><h2 className="mt-2 text-xl font-semibold">{recap.biggestMiss.team}</h2><p className="mt-1 text-sm text-gray-300">Your {recap.biggestMiss.probability}% side lost to {recap.biggestMiss.winner}.</p></> : <p className="mt-2 text-sm text-gray-400">No misses—clean card so far.</p>}</div></section>
        {selectedPool && poolContext ? <section className="mt-6 rounded-2xl border border-blue-900 bg-blue-950/20 p-5"><p className="text-xs uppercase tracking-wider text-blue-400">{selectedPool.name}</p><div className="mt-3 grid gap-4 sm:grid-cols-3"><div><p className="text-sm text-gray-400">Season rank</p><p className="text-2xl font-bold">{poolContext.rank ? `#${poolContext.rank}` : "—"}</p></div><div><p className="text-sm text-gray-400">Movement</p><p className={`text-2xl font-bold ${poolContext.movement > 0 ? "text-emerald-300" : poolContext.movement < 0 ? "text-rose-300" : ""}`}>{poolContext.movement > 0 ? `▲ ${poolContext.movement}` : poolContext.movement < 0 ? `▼ ${Math.abs(poolContext.movement)}` : "—"}</p></div><div><p className="text-sm text-gray-400">Weekly leader</p><p className="text-lg font-semibold">{poolContext.winner ?? "Pending"}</p></div></div></section> : null}
      </>}</> : null}
  </main>;
}
