"use client";
import { useEffect, useState } from "react";
import { getReminderPreferences, saveReminderPreferences } from "@/lib/reminderPreferences";

const TIMEZONES = [["America/Los_Angeles", "Pacific"], ["America/Denver", "Mountain"], ["America/Chicago", "Central"], ["America/New_York", "Eastern"], ["America/Phoenix", "Arizona"], ["America/Anchorage", "Alaska"], ["Pacific/Honolulu", "Hawaii"]] as const;

export function ReminderSettings({ userId }: { userId: string }) {
  const [thursday, setThursday] = useState(false); const [sunday, setSunday] = useState(false);
  const [timezone, setTimezone] = useState(Intl.DateTimeFormat().resolvedOptions().timeZone || "America/Los_Angeles");
  const [hour, setHour] = useState(9); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [status, setStatus] = useState("");
  useEffect(() => { let cancelled = false; getReminderPreferences(userId).then((saved) => { if (!cancelled && saved) { setThursday(saved.thursday_enabled); setSunday(saved.sunday_enabled); setTimezone(saved.timezone); setHour(saved.local_hour); } }).catch((error) => { if (!cancelled) setStatus(error instanceof Error ? error.message : "Unable to load reminders."); }).finally(() => { if (!cancelled) setLoading(false); }); return () => { cancelled = true; }; }, [userId]);
  async function save() { setSaving(true); setStatus(""); try { await saveReminderPreferences({ user_id: userId, thursday_enabled: thursday, sunday_enabled: sunday, timezone, local_hour: hour }); setStatus(thursday || sunday ? "Reminder settings saved." : "Email reminders are off."); } catch (error) { setStatus(error instanceof Error ? error.message : "Unable to save reminders."); } finally { setSaving(false); } }
  return <section className="mt-10 border-t border-gray-800 pt-8" aria-labelledby="reminders-heading"><p className="text-xs font-semibold uppercase tracking-wider text-amber-400">Email</p><h2 id="reminders-heading" className="mt-1 text-2xl font-semibold">Pick Reminders</h2><p className="mt-2 text-sm text-gray-400">Optional reminders are sent only when relevant games remain unpicked.</p>{loading ? <p className="mt-4 text-sm text-gray-500">Loading reminder settings…</p> : <div className="mt-5 max-w-md space-y-4"><label className="flex items-start gap-3 rounded-xl border border-gray-800 bg-gray-950 p-4"><input type="checkbox" checked={thursday} onChange={(event) => setThursday(event.target.checked)} className="mt-1" /><span><span className="block font-medium">Thursday reminder</span><span className="text-sm text-gray-500">Only when a Thursday game is still unpicked.</span></span></label><label className="flex items-start gap-3 rounded-xl border border-gray-800 bg-gray-950 p-4"><input type="checkbox" checked={sunday} onChange={(event) => setSunday(event.target.checked)} className="mt-1" /><span><span className="block font-medium">Sunday reminder</span><span className="text-sm text-gray-500">Lists remaining Sunday and Monday games.</span></span></label><div className="grid gap-3 sm:grid-cols-2"><label className="text-sm text-gray-300">Timezone<select value={timezone} onChange={(event) => setTimezone(event.target.value)} className="mt-1 w-full rounded-lg border border-gray-700 bg-gray-950 p-3 text-white">{TIMEZONES.map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label><label className="text-sm text-gray-300">Send around<select value={hour} onChange={(event) => setHour(Number(event.target.value))} className="mt-1 w-full rounded-lg border border-gray-700 bg-gray-950 p-3 text-white">{[8, 9, 10, 11, 12].map((value) => <option key={value} value={value}>{value > 11 ? "12 PM" : `${value} AM`}</option>)}</select></label></div><button type="button" disabled={saving} onClick={() => void save()} className="w-full rounded-lg bg-blue-600 py-2.5 font-semibold disabled:opacity-50">{saving ? "Saving…" : "Save reminder settings"}</button>{status ? <p className="text-sm text-gray-400" role="status">{status}</p> : null}<p className="text-xs leading-5 text-gray-600">Vercel may begin the daily scheduling job within a one-hour window. Resend handles delivery for your selected local time.</p></div>}</section>;
}
