"use client";
import { useState } from "react";
import { ShareImageButton } from "@/components/ShareImageButton";
import type { PowerRanking } from "@/lib/powerRankings";
import { getTeamTheme } from "@/lib/teamColors";

export function UserRankingEditor({ teams, initialOrder, signedIn, onSave }: { teams: PowerRanking[]; initialOrder: string[] | null; signedIn: boolean; onSave: (order: string[]) => Promise<void> }) {
  const modelOrder = teams.map((team) => team.abbreviation);
  const validInitialOrder = initialOrder?.filter((abbr) => modelOrder.includes(abbr));
  const [order, setOrder] = useState(validInitialOrder?.length === teams.length ? validInitialOrder : modelOrder); const [dragged, setDragged] = useState<string | null>(null); const [status, setStatus] = useState("");
  const byAbbr = new Map(teams.map((team) => [team.abbreviation, team]));
  const ordered = order.map((abbr) => byAbbr.get(abbr)).filter(Boolean) as PowerRanking[];
  const savedOrder = initialOrder?.length === teams.length ? initialOrder : modelOrder;
  const hasUnsavedChanges = order.some((abbr, index) => abbr !== savedOrder[index]);
  function move(from: number, to: number) { if (to < 0 || to >= order.length || from === to) return; setOrder((current) => { const next = [...current]; const [item] = next.splice(from, 1); next.splice(to, 0, item); return next; }); setStatus(""); }
  async function save() { setStatus("Saving…"); try { await onSave(order); setStatus("Saved"); } catch (error) { setStatus(error instanceof Error ? error.message : "Unable to save."); } }
  return <section className="mt-8"><div className="max-w-2xl"><p className="text-xs font-semibold uppercase tracking-wider text-amber-400">Your board</p><h2 className="mt-1 text-2xl font-semibold">My Power Rankings</h2><p className="mt-2 text-sm text-gray-400">Drag teams into place, or use the arrow buttons on mobile. Your share card includes the Top 10.</p></div><div className="mt-5 flex flex-wrap items-center gap-3">{signedIn ? <button type="button" onClick={save} disabled={!hasUnsavedChanges} className="rounded-xl bg-blue-600 px-4 py-2.5 text-sm font-semibold hover:bg-blue-500 disabled:cursor-not-allowed disabled:opacity-50">Save rankings</button> : <a href="/login" className="rounded-xl bg-blue-600 px-4 py-2.5 text-sm font-semibold hover:bg-blue-500">Log in to save</a>}<button type="button" onClick={() => { setOrder(modelOrder); setStatus(""); }} className="rounded-xl border border-gray-700 px-4 py-2.5 text-sm hover:bg-gray-900">Reset to Model</button><ShareImageButton imageUrl={`/api/share/rankings?teams=${encodeURIComponent(order.slice(0, 10).join(","))}`} fileName="pretzel-quest-top-10.png" /><span className={`text-xs ${hasUnsavedChanges ? "text-amber-300" : "text-gray-500"}`}>{signedIn ? hasUnsavedChanges ? "Unsaved changes" : initialOrder ? "Saved" : "Using model order" : "Log in to save changes"}</span>{status ? <span className="text-xs text-gray-400" role="status">{status}</span> : null}</div><div className="mt-6 overflow-hidden rounded-2xl border border-gray-800 bg-gray-950">{ordered.map((team, index) => { const theme = getTeamTheme(team.abbreviation); return <div key={team.id} draggable onDragStart={() => setDragged(team.abbreviation)} onDragOver={(event) => event.preventDefault()} onDrop={() => { if (dragged) move(order.indexOf(dragged), index); setDragged(null); }} className="grid grid-cols-[2.5rem_3.25rem_minmax(0,1fr)_5.5rem] items-center gap-2 border-b border-gray-900 px-3 py-3 last:border-0 sm:px-5"><span className="text-lg font-bold text-gray-500">{index + 1}</span><span className="flex h-9 w-11 items-center justify-center rounded-lg text-xs font-black text-white" style={{ backgroundColor: theme.primary }}>{team.abbreviation}</span><span className="truncate font-semibold">{team.name}</span><span className="flex justify-end gap-1"><button type="button" disabled={index === 0} onClick={() => move(index, index - 1)} aria-label={`Move ${team.name} up`} className="rounded-lg border border-gray-700 px-2.5 py-1.5 disabled:opacity-25">↑</button><button type="button" disabled={index === ordered.length - 1} onClick={() => move(index, index + 1)} aria-label={`Move ${team.name} down`} className="rounded-lg border border-gray-700 px-2.5 py-1.5 disabled:opacity-25">↓</button></span></div>; })}</div></section>;
}
