create table public.sync_runs (
  id bigint generated by default as identity primary key,
  started_at timestamptz not null default now(),
  finished_at timestamptz,
  source text not null check (source in ('cron', 'manual')),
  requested_by uuid references auth.users(id) on delete set null,
  status text not null default 'running' check (status in ('running', 'success', 'error')),
  season integer not null,
  weeks integer[] not null default '{}',
  provider_games integer not null default 0,
  matched integer not null default 0,
  updated integer not null default 0,
  unchanged integer not null default 0,
  unmatched jsonb not null default '[]'::jsonb,
  error text
);

create index sync_runs_started_at_idx on public.sync_runs (started_at desc);

alter table public.sync_runs enable row level security;
grant select on public.sync_runs to authenticated;

create policy "Admins can read sync history"
on public.sync_runs for select
to authenticated
using (
  exists (
    select 1
    from public.profiles
    where profiles.user_id = (select auth.uid())
      and profiles.is_admin = true
  )
);

create table public.favorability_overrides (
  game_id uuid primary key references public.games(id) on delete cascade,
  home_win_probability numeric(5, 4) not null
    check (home_win_probability >= 0.25 and home_win_probability <= 0.75),
  reason text not null check (char_length(trim(reason)) between 3 and 240),
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.favorability_overrides enable row level security;
grant select on public.favorability_overrides to anon, authenticated;

create policy "Favorability overrides are publicly readable"
on public.favorability_overrides for select
to anon, authenticated
using (true);

revoke insert, update, delete on public.sync_runs from anon, authenticated;
revoke insert, update, delete on public.favorability_overrides from anon, authenticated;
